// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4JZVYsdyNOCJYwwO97oVULjNXnfFHSYk',
    appId: '1:52345924540:android:aa22e653ea0a54b41b59b9',
    messagingSenderId: '52345924540',
    projectId: 'kartsyapp-87532',
    storageBucket: 'kartsyapp-87532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABudkujh_GfMFux-CB6qMXcUPn7RVwvvU',
    appId: '1:52345924540:ios:6ff687fabc34fcb81b59b9',
    messagingSenderId: '52345924540',
    projectId: 'kartsyapp-87532',
    storageBucket: 'kartsyapp-87532.firebasestorage.app',
    iosClientId: '52345924540-gmc86dl2ee1k74navpjnhm2dlrejrq8g.apps.googleusercontent.com',
    iosBundleId: 'com.classified.ecommerceShop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6G7mGDXdv8DYr-HIBlXfrit2c_jJykkE',
    appId: '1:507353148295:web:1aaad993c730dd30dc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    authDomain: 'kartsy-3ff24.firebaseapp.com',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
    measurementId: 'G-DNJ2F21Z0P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADwwZ0NJcOPtr17jIP0wNSneJUvm06b7E',
    appId: '1:507353148295:ios:7dc7da17859290aadc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
    iosBundleId: 'com.classified.ecommerceShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6G7mGDXdv8DYr-HIBlXfrit2c_jJykkE',
    appId: '1:507353148295:web:4bc61d14fe0ec172dc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    authDomain: 'kartsy-3ff24.firebaseapp.com',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
    measurementId: 'G-CCBWNYJEEM',
  );

}