// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwYcg6sFanCyxMcPy9KiXvvofcz2f-NKo',
    appId: '1:507353148295:android:ffc2401186d687f5dc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADwwZ0NJcOPtr17jIP0wNSneJUvm06b7E',
    appId: '1:507353148295:ios:7dc7da17859290aadc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
    iosBundleId: 'com.classified.ecommerceShop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6G7mGDXdv8DYr-HIBlXfrit2c_jJykkE',
    appId: '1:507353148295:web:1aaad993c730dd30dc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    authDomain: 'kartsy-3ff24.firebaseapp.com',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
    measurementId: 'G-DNJ2F21Z0P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADwwZ0NJcOPtr17jIP0wNSneJUvm06b7E',
    appId: '1:507353148295:ios:7dc7da17859290aadc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
    iosBundleId: 'com.classified.ecommerceShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6G7mGDXdv8DYr-HIBlXfrit2c_jJykkE',
    appId: '1:507353148295:web:4bc61d14fe0ec172dc8122',
    messagingSenderId: '507353148295',
    projectId: 'kartsy-3ff24',
    authDomain: 'kartsy-3ff24.firebaseapp.com',
    storageBucket: 'kartsy-3ff24.firebasestorage.app',
    measurementId: 'G-CCBWNYJEEM',
  );

}