// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKt5NHM1GvxQUsdIrILd5SBg8FK_tAzjs',
    appId: '1:52345924540:android:512ebc4a491037371b59b9',
    messagingSenderId: '52345924540',
    projectId: 'kartsyapp-87532',
    storageBucket: 'kartsyapp-87532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABudkujh_GfMFux-CB6qMXcUPn7RVwvvU',
    appId: '1:52345924540:ios:6ff687fabc34fcb81b59b9',
    messagingSenderId: '52345924540',
    projectId: 'kartsyapp-87532',
    storageBucket: 'kartsyapp-87532.firebasestorage.app',
    androidClientId: '52345924540-3a9ho54cbrlsacvfnbgqlm511dcsg1it.apps.googleusercontent.com',
    iosClientId: '52345924540-gmc86dl2ee1k74navpjnhm2dlrejrq8g.apps.googleusercontent.com',
    iosBundleId: 'com.classified.ecommerceShop',
  );

}